on:
    push:
        branches:
            - main
        tags-ignore:
            - '**'

name: merge-to-main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env

      - name: Run checks
        uses: ./.github/workflows/run-checks 
      
  docs:
      needs: Quality
      runs-on: ubuntu-latest
      steps:

        - name: Check out
          uses: actions/checkout@v2

        - name: Set up the environment
          uses: ./.github/workflows/setup-poetry-env
          
        - name: Test documentation
          run: |
            source .venv/bin/activate
            make docs-test
            
        - name: Generate documentation
          run: |
            source .venv/bin/activate
            make docs-clean
            make docs-build

        - name: Deploy documentation to GitHub pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.MY_GITHUB_TOKEN }}
            publish_dir: ./docs/_public 